# LLM模型基准测试配置文件

# 模型配置列表
models:
  Qwen_Qwen3-30B-A3B-FP8:
    base_url: "http://10.180.116.2"
    port: 6384
    temperature: 0.7
    extra_body:
      chat_template_kwargs:
        enable_thinking: false

  Qwen_Qwen3-32B-AWQ:
    base_url: "http://10.180.116.2"
    port: 6387
    temperature: 0.7
    extra_body:
      chat_template_kwargs:
        enable_thinking: false

# 可以在这里添加更多模型配置
# deepseek-r1-32b:
#   base_url: "http://10.180.116.5"
#   port: 1004
#   temperature: 0.7