# LLM模型基准测试配置文件

# 模型配置列表
models:
  Your-Model-Name:
    base_url: "http://192.168.172.1"  # 替换为你的模型地址
    port: 1234                        # 替换为你的模型端口
    temperature: 0.7
    extra_body:
      chat_template_kwargs:
        enable_thinking: false        # 为Qwen3系列禁用思考模式

# 可以在这里添加更多模型配置
# deepseek-r1-32b:
#   base_url: "http://10.180.116.5"
#   port: 1004
#   temperature: 0.7